# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pii.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pii.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpii.proto\x12\x0comnibank.pii\"A\n\rRedactRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x12\n\ngiven_name\x18\x03 \x01(\t\"I\n\x0eRedactResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65\x63ision\x18\x02 \x01(\t\x12\x17\n\x0fwarning_message\x18\x03 \x01(\t2P\n\tPiiFilter\x12\x43\n\x06Redact\x12\x1b.omnibank.pii.RedactRequest\x1a\x1c.omnibank.pii.RedactResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pii_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REDACTREQUEST']._serialized_start=27
  _globals['_REDACTREQUEST']._serialized_end=92
  _globals['_REDACTRESPONSE']._serialized_start=94
  _globals['_REDACTRESPONSE']._serialized_end=167
  _globals['_PIIFILTER']._serialized_start=169
  _globals['_PIIFILTER']._serialized_end=249
# @@protoc_insertion_point(module_scope)
